# Generated by Django 5.2 on 2026-01-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('numero_jogadores', models.PositiveIntegerField(help_text='Número de jogadores por equipe')),
                ('categoria', models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino'), ('MISTO', 'Misto')], max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
