# Generated by Django 5.2 on 2026-01-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placar', '0002_modalidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ano', models.PositiveIntegerField(help_text='Ano letivo (ex: 2025)')),
                ('serie', models.CharField(help_text='Ex: 1º Ano, 2º Ano, 9º Ano', max_length=20)),
            ],
            options={
                'unique_together': {('nome', 'ano')},
            },
        ),
    ]
