# Generated by Django 5.2 on 2026-02-04 14:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ano', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Campeonato',
                'verbose_name_plural': 'Campeonatos',
                'ordering': ['-ano', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Misto', 'Misto')], max_length=50)),
                ('possui_placar', models.BooleanField(default=True, help_text='Marque se esta modalidade utiliza placar (ex: futebol).')),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ano', models.PositiveIntegerField(help_text='Ano letivo (ex: 2025)')),
                ('serie', models.CharField(help_text='Ex: 1º Ano', max_length=20)),
                ('logo', models.ImageField(blank=True, help_text='Logo da equipe (JPG, opcional)', null=True, upload_to='equipes/logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg'])])),
            ],
            options={
                'unique_together': {('nome', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='Danca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_apresentacao', models.DateField()),
                ('horario_apresentacao', models.TimeField()),
                ('colocacao', models.IntegerField(blank=True, choices=[(1, '1º Lugar'), (2, '2º Lugar'), (3, '3º Lugar'), (4, '4º Lugar'), (5, '5º Lugar'), (6, '6º Lugar'), (7, '7º Lugar'), (8, '8º Lugar'), (9, '9º Lugar'), (10, '10º Lugar'), (11, '11º Lugar'), (12, '12º Lugar'), (0, 'Desclassificada')], null=True)),
                ('observacoes', models.CharField(blank=True, null=True)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dancas', to='placar.campeonato')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apresentacoes', to='placar.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocorrencia', models.IntegerField(blank=True, choices=[(1, 'Doações'), (2, 'Penalidades')], null=True)),
                ('pontos', models.IntegerField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontosextras', to='placar.campeonato')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos_extras', to='placar.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('OIT', 'Oitavas de Final'), ('QUA', 'Quartas de Final'), ('SEM', 'Semifinal'), ('FIN', 'Final')], max_length=3)),
                ('data', models.DateTimeField(verbose_name='Data e horário')),
                ('houve_wo', models.BooleanField(default=False, help_text='Preencha ao iniciar a partida. Irá habilitar ou não  o placar.', verbose_name='Houve WO?')),
                ('placar_a', models.IntegerField(blank=True, null=True, verbose_name='Placar Equipe A')),
                ('placar_b', models.IntegerField(blank=True, null=True, verbose_name='Placar Equipe B')),
                ('encerrada', models.BooleanField(default=False, verbose_name='Partida encerrada')),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='placar.campeonato')),
                ('equipe_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_equipe_a', to='placar.equipe', verbose_name='Equipe A')),
                ('equipe_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_equipe_b', to='placar.equipe', verbose_name='Equipe B')),
                ('equipe_wo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wos', to='placar.equipe', verbose_name='Equipe WO')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modalidade', to='placar.modalidade')),
                ('vencedora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vitorias', to='placar.equipe', verbose_name='Equipe vencedora')),
            ],
        ),
    ]
