# Generated by Django 5.2 on 2026-02-02 17:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino'), ('MISTO', 'Misto')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ano', models.PositiveIntegerField(help_text='Ano letivo (ex: 2025)')),
                ('serie', models.CharField(help_text='Ex: 1º Ano', max_length=20)),
                ('logo', models.ImageField(blank=True, help_text='Logo da equipe (JPG, opcional)', null=True, upload_to='equipes/logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg'])])),
            ],
            options={
                'unique_together': {('nome', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('OIT', 'Oitavas de Final'), ('QUA', 'Quartas de Final'), ('SEM', 'Semifinal'), ('FIN', 'Final')], max_length=3)),
                ('data', models.DateTimeField(verbose_name='Data e horário')),
                ('placar_a', models.IntegerField(blank=True, default=0, null=True, verbose_name='Placar Equipe A')),
                ('placar_b', models.IntegerField(blank=True, default=0, null=True, verbose_name='Placar Equipe B')),
                ('gols_contra_a', models.IntegerField(blank=True, default=0, null=True, verbose_name='Gols contra Equipe A')),
                ('gols_contra_b', models.IntegerField(blank=True, default=0, null=True, verbose_name='Gols contra Equipe B')),
                ('pontuacao_a', models.IntegerField(default=0, verbose_name='Pontuação Equipe A')),
                ('pontuacao_b', models.IntegerField(default=0, verbose_name='Pontuação Equipe B')),
                ('houve_wo', models.BooleanField(default=False, verbose_name='Houve WO?')),
                ('encerrada', models.BooleanField(default=False, verbose_name='Partida encerrada?')),
                ('equipe_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_equipe_a', to='placar.equipe', verbose_name='Equipe A')),
                ('equipe_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_equipe_b', to='placar.equipe', verbose_name='Equipe B')),
                ('equipe_wo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wos', to='placar.equipe', verbose_name='Equipe WO')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modalidade', to='placar.modalidade')),
                ('vencedora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vitorias', to='placar.equipe', verbose_name='Equipe vencedora')),
            ],
        ),
    ]
