# Generated by Django 5.2 on 2026-02-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extra',
            options={'verbose_name': 'Doação ou penalidade', 'verbose_name_plural': 'Doações ou penalidades'},
        ),
        migrations.AlterField(
            model_name='equipe',
            name='ano',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='serie',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='modalidade',
            name='possui_placar',
            field=models.BooleanField(default=True, help_text='Desmarque se esta modalidade não utiliza placar (ex: Xadrez).'),
        ),
    ]
