# Generated by Django 5.2 on 2026-02-05 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placar', '0002_alter_extra_options_alter_equipe_ano_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='horario',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário'),
        ),
        migrations.AlterField(
            model_name='danca',
            name='observacoes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='extra',
            name='observacoes',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='partida',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='equipe_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidas_equipe_a', to='placar.equipe', verbose_name='Equipe A'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='equipe_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidas_equipe_b', to='placar.equipe', verbose_name='Equipe B'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='fase',
            field=models.CharField(choices=[('OIT', 'Oitavas de Final'), ('QUA', 'Quartas de Final'), ('SEM', 'Semifinal'), ('TER', 'Terceiro Lugar'), ('FIN', 'Final')], max_length=3),
        ),
    ]
