# Generated by Django 5.2 on 2026-02-03 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placar', '0002_campeonato_alter_modalidade_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='gols_contra_a',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='gols_contra_b',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='pontuacao_a',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='pontuacao_b',
        ),
        migrations.AddField(
            model_name='partida',
            name='campeonato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='placar.campeonato'),
            preserve_default=False,
        ),
    ]
