# Generated by Django 5.2 on 2026-02-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placar', '0003_remove_partida_gols_contra_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='houve_wo',
            field=models.BooleanField(default=False, help_text='Preencha ao iniciar a partida. Irá habilitar ou não  o placar.', verbose_name='Houve WO?'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='placar_a',
            field=models.IntegerField(blank=True, null=True, verbose_name='Placar Equipe A'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='placar_b',
            field=models.IntegerField(blank=True, null=True, verbose_name='Placar Equipe B'),
        ),
    ]
