# Generated by Django 5.2 on 2026-02-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placar', '0003_partida_horario_alter_danca_observacoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='numero',
            field=models.CharField(choices=[('PRI', '1ª'), ('SEG', '2ª'), ('TER', '3ª'), ('QUA', '4ª'), ('QUI', '5ª'), ('SEX', '6ª'), ('SET', '7ª'), ('OIT', '8ª'), ('NON', '9ª'), ('DEC', '10ª'), ('DECPRI', '11ª'), ('DECSEG', '12ª'), ('DECTEC', '13ª'), ('DECQUA', '14ª')], default=1, max_length=6),
            preserve_default=False,
        ),
    ]
