# Generated by Django 5.2 on 2026-02-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placar', '0004_partida_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='iniciada',
            field=models.BooleanField(default=False, verbose_name='Partida iniciada'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='numero',
            field=models.CharField(choices=[('PRI', '1ª'), ('SEG', '2ª'), ('TER', '3ª'), ('QUA', '4ª'), ('QUI', '5ª'), ('SEX', '6ª'), ('SET', '7ª'), ('OIT', '8ª'), ('NON', '9ª'), ('DEC', '10ª'), ('DECPRI', '11ª'), ('DECSEG', '12ª'), ('DECTEC', '13ª'), ('DECQUA', '14ª')], max_length=6, verbose_name='Número da partida'),
        ),
    ]
