# Generated by Django 5.2 on 2026-02-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placar', '0004_alter_partida_houve_wo_alter_partida_placar_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalidade',
            name='possui_placar',
            field=models.BooleanField(default=True, help_text='Marque se esta modalidade utiliza placar (ex: futebol).'),
        ),
    ]
