# Generated by Django 5.2 on 2026-02-03 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placar', '0005_modalidade_possui_placar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Danca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_apresentacao', models.DateField()),
                ('horario_apresentacao', models.TimeField()),
                ('colocacao', models.PositiveSmallIntegerField(choices=[(1, '1º Lugar'), (2, '2º Lugar'), (3, '3º Lugar'), (4, '4º Lugar'), (5, '5º Lugar'), (6, '6º Lugar'), (7, '7º Lugar'), (8, '8º Lugar'), (9, '9º Lugar'), (10, '10º Lugar'), (11, '11º Lugar'), (12, '12º Lugar')])),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apresentacoes', to='placar.equipe')),
            ],
        ),
    ]
