# Generated by Django 5.2 on 2026-02-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placar', '0005_partida_iniciada_alter_partida_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='numero',
            field=models.CharField(choices=[('PRI', '1ª'), ('SEG', '2ª'), ('TER', '3ª'), ('QUA', '4ª'), ('QUI', '5ª'), ('SEX', '6ª'), ('SET', '7ª'), ('OIT', '8ª'), ('NON', '9ª'), ('DEC', '10ª'), ('DECPRI', '11ª'), ('DECSEG', '12ª')], max_length=6, verbose_name='Número da partida'),
        ),
    ]
