# Generated by Django 5.2 on 2026-02-05 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placar', '0009_alter_partida_houve_wo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='houve_wo',
            field=models.BooleanField(default=False, help_text='Preencha ao iniciar a partida. Irá habilitar ou não  o placar.', verbose_name='Houve WO?'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='modalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modalidade', to='placar.modalidade'),
        ),
    ]
