# Generated by Django 5.2 on 2026-02-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placar', '0012_alter_partida_houve_wo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='houve_wo',
            field=models.BooleanField(blank=True, help_text='Preencha ao iniciar a partida. Irá habilitar ou não  o placar.', null=True, verbose_name='Houve WO?'),
        ),
    ]
