# Generated by Django 5.2 on 2026-02-05 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placar', '0013_alter_partida_houve_wo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='modalidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modalidade', to='placar.modalidade'),
        ),
    ]
