# Generated by Django 5.2 on 2026-02-05 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placar', '0014_alter_partida_modalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='campeonato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='placar.campeonato'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='fase',
            field=models.CharField(blank=True, choices=[('OIT', 'Oitavas de Final'), ('QUA', 'Quartas de Final'), ('SEM', 'Semifinal'), ('TER', 'Terceiro Lugar'), ('FIN', 'Final')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='partida',
            name='numero',
            field=models.CharField(blank=True, choices=[('PRI', '1ª'), ('SEG', '2ª'), ('TER', '3ª'), ('QUA', '4ª'), ('QUI', '5ª'), ('SEX', '6ª'), ('SET', '7ª'), ('OIT', '8ª'), ('NON', '9ª'), ('DEC', '10ª'), ('DECPRI', '11ª'), ('DECSEG', '12ª')], max_length=6, null=True, verbose_name='Número da partida'),
        ),
        migrations.AddConstraint(
            model_name='partida',
            constraint=models.UniqueConstraint(fields=('campeonato', 'modalidade', 'numero'), name='unique_partida_por_campeonato_modalidade_numero'),
        ),
    ]
