# Generated by Django 5.2 on 2026-02-06 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placar', '0015_alter_partida_campeonato_alter_partida_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalidade',
            name='desempate',
            field=models.CharField(choices=[('PRORROGACAO', 'Prorrogação'), ('ULTIMOSET', 'Último set'), ('PENALTIS', 'Penaltis'), ('LANCESLIVRES', 'Lances livres')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modalidade',
            name='header',
            field=models.ImageField(default=1, help_text='Header da página da modalidade)', upload_to='equipes/logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg'])]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partida',
            name='set_dois_a',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pontuação Set 2 Equipe A'),
        ),
        migrations.AddField(
            model_name='partida',
            name='set_dois_b',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pontuação Set 2 Equipe B'),
        ),
        migrations.AddField(
            model_name='partida',
            name='set_tres_a',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pontuação Set 3 Equipe A'),
        ),
        migrations.AddField(
            model_name='partida',
            name='set_tres_b',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pontuação Set 3 Equipe B'),
        ),
        migrations.AddField(
            model_name='partida',
            name='set_um_a',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pontuação Set 1 Equipe A'),
        ),
        migrations.AddField(
            model_name='partida',
            name='set_um_b',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pontuação Set 1 Equipe B'),
        ),
    ]
