# Generated by Django 5.2 on 2026-02-06 12:49

import django.core.validators
import placar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placar', '0016_modalidade_desempate_modalidade_header_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeonato',
            name='footer_ranking',
            field=models.ImageField(blank=True, help_text='Footer do ranking', null=True, upload_to=placar.models.ranking_footer_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='header_ranking',
            field=models.ImageField(blank=True, help_text='Header do ranking', null=True, upload_to=placar.models.ranking_header_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo da equipe (JPG ou PNG, opcional)', null=True, upload_to='equipes/logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='modalidade',
            name='desempate',
            field=models.CharField(choices=[('PRORROGACAO', 'Prorrogação'), ('ULTIMOSET', 'Último set'), ('PENALTIS', 'Pênaltis'), ('LANCESLIVRES', 'Lances livres')]),
        ),
    ]
