# Generated by Django 5.2 on 2026-02-06 16:22

import django.core.validators
import placar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placar', '0017_campeonato_footer_ranking_campeonato_header_ranking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modalidade',
            name='desempate',
        ),
        migrations.AddField(
            model_name='modalidade',
            name='possui_sets',
            field=models.BooleanField(default=False, help_text='Marque se esta modalidade utiliza sets (ex: Volei).'),
        ),
        migrations.AddField(
            model_name='partida',
            name='desempate_a',
            field=models.IntegerField(blank=True, null=True, verbose_name='Placar para desempate (por penaltis ou lances livre) -Equipe A'),
        ),
        migrations.AddField(
            model_name='partida',
            name='desempate_b',
            field=models.IntegerField(blank=True, null=True, verbose_name='Placar para desempate (por penaltis ou lances livre) -Equipe B'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo da equipe (PNG)', null=True, upload_to=placar.models.logo_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'])]),
        ),
        migrations.AlterField(
            model_name='modalidade',
            name='header',
            field=models.ImageField(blank=True, help_text='Header da página da modalidade)', null=True, upload_to=placar.models.logo_mod_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'])]),
        ),
    ]
