# Generated by Django 5.2 on 2026-02-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placar', '0018_remove_modalidade_desempate_modalidade_possui_sets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='set_dois_a',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='set_dois_b',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='set_tres_a',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='set_tres_b',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='set_um_a',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='set_um_b',
        ),
        migrations.AddField(
            model_name='partida',
            name='set_a',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pontuação Set Equipe A'),
        ),
        migrations.AddField(
            model_name='partida',
            name='set_b',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pontuação Set Equipe B'),
        ),
        migrations.AddField(
            model_name='partida',
            name='set_encerrado',
            field=models.BooleanField(default=False, verbose_name='Set encerrado'),
        ),
    ]
