# Generated by Django 5.2 on 2026-02-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placar', '0019_remove_partida_set_dois_a_remove_partida_set_dois_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='houve_empate',
            field=models.BooleanField(blank=True, help_text='Preencha se encerrou o tempo da partida com empate. Irá habilitar o placar de desempate.', null=True, verbose_name='Houve empate?'),
        ),
    ]
