# Generated by Django 5.2 on 2026-02-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placar', '0020_partida_houve_empate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='set_a',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='set_b',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='set_encerrado',
        ),
        migrations.AddField(
            model_name='partida',
            name='primeiroset_a',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pontuação Primeiro Set Equipe A'),
        ),
        migrations.AddField(
            model_name='partida',
            name='primeiroset_b',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pontuação Primeiro Set Equipe B'),
        ),
        migrations.AddField(
            model_name='partida',
            name='segundoset_a',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pontuação Segundo Set Equipe A'),
        ),
        migrations.AddField(
            model_name='partida',
            name='segundoset_b',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pontuação Segundo Set Equipe B'),
        ),
        migrations.AddField(
            model_name='partida',
            name='terceiroset_a',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pontuação Terceiro Set Equipe A'),
        ),
        migrations.AddField(
            model_name='partida',
            name='terceiroset_b',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pontuação Terceiro Set Equipe B'),
        ),
    ]
